controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

test-bundle-controller:
    resource: ../../src/TSF/TestBundle/Controller/
    type: annotation
